th_date_converter_julian:
    path:     /julian
    defaults: { _controller: THDateConverterBundle:Julian:index }
th_date_converter_gregorian:
    path:     /gregorian
    defaults: { _controller: THDateConverterBundle:Gregorian:index }
th_date_easter:
    path:     /easter
    defaults: { _controller: THDateConverterBundle:Easter:index }
th_date_addking:
    path:     /addKing
    defaults: { _controller: THDateConverterBundle:King:addKing }
th_date_king:
    path:     /king
    defaults: { _controller: THDateConverterBundle:King:index }
th_documentation:
    path:     /documentation
    defaults: { _controller: THDateConverterBundle:Documentation:index }
th_french_calendar:
    path:     /french_republican
    defaults: { _controller: THDateConverterBundle:FrenchRepublican:index }
th_christian_feast:
    path:     /christian_feast
    defaults: { _controller: THDateConverterBundle:ChristianFeast:index }