parameters:
#    th_date_converter.example.class: TH\DateConverter\Bundle\Example

services:
#    th_date_converter.example:
#        class: %th_date_converter.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
